image: ubuntu/lts
packages:
  - golang-go
sources:
  - https://git.sr.ht/~mytec/gosched
tasks:
  - compile: |
      cd gosched
      go build ./...
  - test: |
      cd gosched
      go test ./...
  - vet: |
      cd gosched
      go vet ./...
  - staticcheck: |
      go install honnef.co/go/tools/cmd/staticcheck@latest
      cd gosched
      "$(go env GOPATH)/bin/staticcheck" ./...
  - build-linux: |
      cd gosched
      go build -o gosched-linux-amd64 ./cmd/gosched
  - build-darwin: |
      cd gosched
      GOOS=darwin GOARCH=arm64 go build -o gosched-darwin-arm64 ./cmd/gosched      
  - build-freebsd: |
      cd gosched
      GOOS=freebsd GOARCH=amd64 go build -o gosched-freebsd-amd64 ./cmd/gosched      
  - build-openbsd: |
      cd gosched
      GOOS=openbsd GOARCH=amd64 go build -o gosched-openbsd-amd64 ./cmd/gosched
  - build-windows: |
      cd gosched
      GOOS=windows GOARCH=amd64 go build -o gosched-windows-amd64 ./cmd/gosched
  - build-testprog-linux: |
      cd gosched
      go build -o testprog-linux-amd64 ./cmd/testprog
  - build-testprog-darwin: |
      cd gosched
      GOOS=darwin GOARCH=arm64 go build -o testprog-darwin-arm64 ./cmd/testprog
  - build-testprog-freebsd: |
      cd gosched
      GOOS=freebsd GOARCH=amd64 go build -o testprog-freebsd-amd64 ./cmd/testprog      
  - build-testprog-openbsd: |
      cd gosched
      GOOS=openbsd GOARCH=amd64 go build -o testprog-openbsd-amd64 ./cmd/testprog
  - build-testprog-windows: |
      cd gosched
      GOOS=windows GOARCH=amd64 go build -o testprog-windows-amd64 ./cmd/testprog            
triggers:
  - action: email
    condition: always
    to: sourcehut@bogoflop.com
