image: freebsd/latest
packages:
  - go
sources:
  - https://git.sr.ht/~mytec/gosched
tasks:
  - compile: |
      cd gosched
      go build ./...
  - test: |
      cd gosched
      go test ./...
  - build-freebsd: |
      cd gosched
      go build -o gosched-freebsd-amd64 ./cmd/gosched
  - build-testprog-freebsd: |
      cd gosched
      go build -o testprog-freebsd-amd64 ./cmd/testprog      
triggers:
  - action: email
    condition: always
    to: sourcehut@bogoflop.com