image: openbsd/latest
packages:
  - go
sources:
  - https://git.sr.ht/~mytec/gosched
tasks:
  - compile: |
      cd gosched
      go build ./...
  - test: |
      cd gosched
      go test ./...
  - build-openbsd: |
      cd gosched
      go build -o gosched-openbsd-amd64 ./cmd/gosched
  - build-testprog-openbsd: |
      cd gosched
      go build -o testprog-openbsd-amd64 ./cmd/testprog       
triggers:
  - action: email
    condition: always
    to: sourcehut@bogoflop.com