image: openbsd/latest
packages:
  - go
sources:
  - https://git.sr.ht/~mytec/gosched
tasks:
  - compile: |
      cd gosched
      go build ./...
  - test: |
      cd gosched
      go test ./...
triggers:
  - action: email
    condition: always
    to: sourcehut@bogoflop.com